version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geothermai
    volumes:
      - ./app:/app
    ports:
      - "8080:80"
    networks:
      - defaultnetwork
    user: $UID:$GID

networks:
    defaultnetwork:
        driver: bridge
